name: Build CSV Fixer Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Download Wix Toolset
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix311-binaries.zip"
          Expand-Archive -Path "wix311-binaries.zip" -DestinationPath "./wixtoolset"
  
      - name: Add Wix Toolset to PATH
        run: echo "./wixtoolset" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8 

      - name: Publish GUI
        run: |
          cd ./CSVFixConfigurator
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true --output ../publish/gui

      - name: Publish Service
        run: |
          cd ./CSVFixService
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true --output ../publish/service

      - name: Delete pdb files
        run: |
          
      - name: Package Installer
        run: |
          candle ./Installer/WiXConfig.wxs -out ./Installer/WiXConfig.wixobj
          light ./Installer/WiXConfig.wixobj -ext WixUtilExtension -ext WixUIExtension -b ./ -o ./publish/install/installer.msi

          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish/install/installer.msi
          retention-days: 14

